[tool.poetry]
name = "spacialsound"
version = "0.1.0"
description = ""
authors = ["clz13087 <clz13087@nitech.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
